# Generated by Django 5.1.5 on 2025-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_pan_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
